version: '1'
services:
  mysql:
    image: rethinkdb:latest
    restart: always
    container_name: rethinkdb
    ports:
      - '8080:8080'
      - '28015:28015'
      - '55001:55001'
  mongo-container:
    image: mongo:3.4.2
    environment:
        # provide your credentials here
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=rootPassXXX
    ports:
      - "27017:27017"
